### ISSUE TITLE
help with my code

### ISSUE THREAD

**Issue by projetoarduino** [peterhinch/micropython_remote#7]
Hello, I'm using your code but it doesn't deliver an address (id), so I started working on some modifications to a code that I already used in the arduino, with this something that looks like an address, but the Anti-Code that would be the 1010 at the end or beginning of the code is not valid and I can't extract the data or button1 and button2.

Would you help me ?

https://github.com/projetoarduino/rf433-ht6p20-micropython

**Comment by peterhinch** [comment]
The code you link to does not use this library, so this query should be raised in [Discussions](https://github.com/micropython/micropython/discussions) not in this bug tracker.

If anyone is to help, you need to give a much clearer description of what you are trying to do, what hardware you are using, and what is the outcome when you run your code.
