### ISSUE TITLE
ESP8266 Support

### ISSUE THREAD

**Issue by ErfanPY** [peterhinch/micropython_remote#8]
Hello there, Can you add ESP8266 support to this library ? What is the problem that doesn't make ESP8266 compatible ?

**Comment by peterhinch** [comment]
In my testing the ESP8266 could not achieve the required timing accuracy, which is very tight. The transmitter uses special hardware (the ESP32 RMT device, and the RP2040 PIO). The ESP8266 possesses no equivalent. Sorry.
